version: '3.8'

services:
  backend:
    image: client:0.0.1
    build: ./SumPractBackV1
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_NAME=test
      - DATABASE_HOST=db
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "15432:5432"
    restart: always

  frontend:
    build: ./summer-open-code-frontend
    environment:
      - NEXT_PUBLIC_API=/api
    restart: always

  nginx:
    image: nginx
    ports:
      - 83:83
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
